all:
	pdflatex -shell-escape valais.19.els.slides

clean:
	$(RM) -r _minted*
	$(RM) valais.19.els.slides.aux valais.19.els.slides.log valais.19.els.slides.nav valais.19.els.slides.out valais.19.els.slides.pdf valais.19.els.slides.snm valais.19.els.slides.toc valais.19.els.slides.vrb
